/* Recursive Descent Parser implementation (statement)
 *
 * The recursive descent parser is implemented as a set of mutually recursive
 * functions for each rule in the grammar. This file provides functions for
 * rules in the 'statement' set.
 *
 * Generated by generate_recursive_parser.py on 2020-03-24.
 */

#include <stddef.h>

#include "ast.h"
#include "parser.h"

ExprAstNode* Parser_statement(Parser* parser) {  // @TODO
  /*
   * labeled_statement
   * compound_statement
   * expression_statement
   * selection_statement
   * iteration_statement
   * jump_statement
   */

  return NULL;
}
ExprAstNode* Parser_labeled_statement(Parser* parser) {  // @TODO
  /*
   * IDENTIFIER ':' statement
   * CASE constant_expression ':' statement
   * DEFAULT ':' statement
   */

  return NULL;
}
ExprAstNode* Parser_compound_statement(Parser* parser) {  // @TODO
  /*
   * '{' '}'
   * '{'  block_item_list '}'
   */

  return NULL;
}
ExprAstNode* Parser_block_item_list(Parser* parser) {  // @TODO
  /*
   * block_item
   * block_item_list block_item
   */

  return NULL;
}
ExprAstNode* Parser_block_item(Parser* parser) {  // @TODO
  /*
   * declaration
   * statement
   */

  return NULL;
}
ExprAstNode* Parser_expression_statement(Parser* parser) {  // @TODO
  /*
   * '
   */

  return NULL;
}
ExprAstNode* Parser_selection_statement(Parser* parser) {  // @TODO
  /*
   * IF '(' expression ')' statement ELSE statement
   * IF '(' expression ')' statement
   * SWITCH '(' expression ')' statement
   */

  return NULL;
}
ExprAstNode* Parser_iteration_statement(Parser* parser) {  // @TODO
  /*
   * WHILE '(' expression ')' statement
   * DO statement WHILE '(' expression ')' '
   */

  return NULL;
}
ExprAstNode* Parser_jump_statement(Parser* parser) {  // @TODO
  /*
   * GOTO IDENTIFIER '
   */

  return NULL;
}
